### PR TITLE
Allow Options with only short or long flags

### LINKED ISSUE #22: shortFlag XOR longFlag possibility
One thing that happens with having `shortFlag` be mandatory is that since its only a single character, you quickly get collisions, and thus are forced to use random characters for an option (`-y, --check-file`). I think in such a case, it would be better to have the option to specify only a `longFlag`. You could make a case for the other direction too of course, thus I'm thinking it be useful to have the ability to exclusively choose a `shortFlag` or `longFlag` for an `Option`.

### PR DESCRIPTION
**Pull request by jatoben**
In some cases, Options with only a short flag (`-f`) or long flag (`--file`) are useful.

Closes #22.

### CODE REVIEW

**Comment by beltex** [comment]
One thought on this, rather than the convenience initializers, what about having a default value of `nil` for `shortFlag` and `longFlag`? Just as `required` now has a default value of `false` to save on those extra inits that `BoolOption` & `CounterOption` had (great catch BTW!). Here's the diff (tests pass).

```diff
diff --git a/CommandLine/Option.swift b/CommandLine/Option.swift
index e39e13d..ec389dc 100644
--- a/CommandLine/Option.swift
+++ b/CommandLine/Option.swift
@@ -46,7 +46,7 @@ public class Option {
     return false
   }
   
-  private init(_ shortFlag: String?, _ longFlag: String?, _ required: Bool, _ helpMessage: String) {
+  public init(shortFlag: String? = nil, longFlag: String? = nil, required: Bool = false, helpMessage: String) {
     if let sf = shortFlag {
       assert(sf.characters.count == 1, "Short flag must be a single character")
       assert(Int(sf) == nil && sf.toDouble() == nil, "Short flag cannot be a numeric value")
@@ -61,26 +61,7 @@ public class Option {
     self.helpMessage = helpMessage
     self.required = required
   }
-  
-  /* The optional casts in these initalizers force them to call the private initializer. Without
-   * the casts, they recursively call themselves.
-   */
-  
-  /** Initializes a new Option that has both long and short flags. */
-  public convenience init(shortFlag: String, longFlag: String, required: Bool = false, helpMessage: String) {
-    self.init(shortFlag as String?, longFlag, required, helpMessage)
-  }
-  
-  /** Initializes a new Option that has only a short flag. */
-  public convenience init(shortFlag: String, required: Bool = false, helpMessage: String) {
-    self.init(shortFlag as String?, nil, required, helpMessage)
-  }
-  
-  /** Initializes a new Option that has only a long flag. */
-  public convenience init(longFlag: String, required: Bool = false, helpMessage: String) {
-    self.init(nil, longFlag as String?, required, helpMessage)
-  }
-  
+
   func flagMatch(flag: String) -> Bool {
     return flag == shortFlag || flag == longFlag
   }
@@ -245,25 +226,10 @@ public class EnumOption<T:RawRepresentable where T.RawValue == String>: Option {
    * of Xcode 7 beta 2.
    */
   
-  private override init(_ shortFlag: String?, _ longFlag: String?, _ required: Bool, _ helpMessage: String) {
-    super.init(shortFlag, longFlag, required, helpMessage)
-  }
-  
-  /** Initializes a new Option that has both long and short flags. */
-  public convenience init(shortFlag: String, longFlag: String, required: Bool = false, helpMessage: String) {
-    self.init(shortFlag as String?, longFlag, required, helpMessage)
-  }
-  
-  /** Initializes a new Option that has only a short flag. */
-  public convenience init(shortFlag: String, required: Bool = false, helpMessage: String) {
-    self.init(shortFlag as String?, nil, required, helpMessage)
+  public override init(shortFlag: String? = nil, longFlag: String? = nil, required: Bool = false, helpMessage: String) {
+    super.init(shortFlag: shortFlag, longFlag: longFlag, required: required, helpMessage: helpMessage)
   }
-  
-  /** Initializes a new Option that has only a long flag. */
-  public convenience init(longFlag: String, required: Bool = false, helpMessage: String) {
-    self.init(nil, longFlag as String?, required, helpMessage)
-  }
-  
+
   override func setValue(values: [String]) -> Bool {
     if values.count == 0 {
       return false
```

**Comment by jatoben** [comment]
@beltex I don't love the extra initializer methods, but I think they make it clearer for users of the library, especially when viewing the generated interface in Xcode. Also, actively preventing an invalid combination of parameters (both shortFlag and longFlag being nil) rather than raising an assertion if that happens fits better with Swift style IMO.

**Comment by beltex** [comment]
@jatoben Good points. Indeed, I do wish Xcode made it clearer that a parameter has a default value in the generated interface.

**Comment by beltex** [comment]
@jatoben Noticed something else just now, `ParseError.description` doesn't handle `longFlag` being optional. So you get either of these:

```bash
Invalid value(s) for option nil:

# Or

Invalid value(s) for option Optional("file"):
```

Here’s one way to address that via nil coalescing:

```diff
diff --git a/CommandLine/CommandLine.swift b/CommandLine/CommandLine.swift
index f2fd8dc..5624ecb 100644
--- a/CommandLine/CommandLine.swift
+++ b/CommandLine/CommandLine.swift
@@ -71,9 +71,9 @@ public class CommandLine {
         return "Invalid argument: \(arg)"
       case let .InvalidValueForOption(opt, vals):
         let vs = ", ".join(vals)
-        return "Invalid value(s) for option \(opt.longFlag): \(vs)"
+        return "Invalid value(s) for option \(opt.longFlag ?? opt.shortFlag!): \(vs)"
       case let .MissingRequiredOptions(opts):
-        return "Missing required options: \(opts.map { return $0.longFlag })"
+        return "Missing required options: \(opts.map { return $0.longFlag ?? $0.shortFlag! })"
 
       }
     }
```

**Comment by jatoben** [comment]
Oof, nice catch @beltex.

**Comment by beltex** [comment]
@jatoben np! :)

**Pull request merged**
