### PR TITLE
Add compatibility with Swift 3 (May 9th) snapshot

### PR DESCRIPTION
**Pull request by IngmarStein**
Here's another take on Swift 3 support, based on your current HEAD.

I used `#if swift(>=3.0)` blocks to maintain Swift 2.2 support, but it's apparent that this is a compiler feature and not a preprocessor, e.g. it's not possible to have something like this:
```
#if swift(>=3.0)
  private struct StderrOutputStream: OutputStream {
#else
  private struct StderrOutputStream: OutputStreamType {
#endif
```
In that case, I had to duplicate the whole (tiny) struct.

### CODE REVIEW

**Comment by IngmarStein** [comment]
The updated Swift snapshot Linux required quite a few changes I didn't expect, but the tests pass now.

**Comment by IngmarStein** [comment]
Recognizing that the required changes seem to become more extensive with every Swift snapshot, they might be better off in a separate branch. Except, of course, when the plan is to offer the same CommandLine release to both Swift 2 and Swift 3 users at the same time.

**Comment by glessard** [comment]
The various invocation of `stride()` that use `by: 1` might as well be switched to range operators. Those will work with either version, and reduce the number of `#if` statements.

**Comment by IngmarStein** [comment]
Good find. I've updated the PR accordingly.

**Comment by glessard** [comment]
Another one: the pattern matching with multiple optionals could also sidestep the change in spelling of `.some` and `.none` by using `case let (sf?, nil)` instead of `case let (.some(sf), .none)`

**Comment by glessard** [comment]
And finally, there are a lot of cases where an entire function is duplicated not because of an incompatibility, but because it would cause a warning from the Swift 2.2 compiler. (e.g. `func setValue(_ value: T)`) In such cases, the warning might be a lesser evil than duplication.

**Comment by glessard** [comment]
It appears that ErrorType/ErrorProtocol can be added to an enum in an extension.
(It works in a 2.2 playground)
Doing this would reduce the amount of duplication.

**Comment by IngmarStein** [comment]
With respect to adding ErrorType/ErrorProtocol in an extension: in order to comply with the Swift 3 style guide, enum values should use lowerCamelCase. We couldn't do that without duplicating the body.
Right now, my aim was to compile cleanly without warning in both languages even if that adds some more duplication. I'd like the repo owner to chime in where he wants to strike the balance.

**Comment by glessard** [comment]
That's a good point, though there's a plenty of the current API that doesn't match the style guide apart from the enums (e.g. `splitByCharacter`). I was mostly thinking of reducing duplication =)

**Comment by IngmarStein** [comment]
@jatoben I've squashed the commits to remove the intermediate updates and rebased on the current HEAD to make for an easy merge.

**Comment by jatoben** [comment]
Sorry for being late to the party here, and thanks so much for doing the heavy lifting!

> Right now, my aim was to compile cleanly without warning in both languages even if that adds some more duplication. I'd like the repo owner to chime in where he wants to strike the balance.

Definitely 👍on this. I'm not too concerned about duplication, since when Swift 3 ships, I expect that folks will convert pretty quickly, and we can just delete the `#else` blocks. The old releases will still be around for anyone who wants to use Swift 2.

> though there's a plenty of the current API that doesn't match the style guide apart from the enums (e.g. splitByCharacter)

That method name dates from August 2014 😄 The code could most definitely use a good refactoring, which I'll probably tackle after the Swift 3 release. If anyone wants to take a pass at it before then though, please go ahead.

**Pull request merged**
