### PR TITLE
Fixes for tests with Swift 2.2

### PR DESCRIPTION
**Pull request by glessard**
(at least the December 1st toolchain.)

### CODE REVIEW

**Comment by jatoben** [comment]
Thanks @glessard! I didn't need all of these commits, so I cherry-picked a few into my branch. The 2015-12-10 snapshot [mostly works](https://github.com/jatoben/CommandLine/blob/852385b4d852dc8675e25fa0be68af3d826e93ad/CommandLineTests/CommandLineTests.swift#L27) on Linux now :smiley_cat:

**Comment by glessard** [comment]
I still get crashes when running tests using the 2015-12-10 snapshot with Xcode 7.2 -- the same I'd solved with commit b8ce93b. Do you not see those?

**Comment by jatoben** [comment]
Since stock Xcode works fine, I'm a bit hesitant to add a temporary hack that would just be reverted later. Do you see any big advantages when using Swift 2.2-dev on OS X, other than the Swift package manager? (I know that's a major draw.)

**Comment by glessard** [comment]
I concede that at the moment, there aren't big advantages. I'm expecting the advantages to start accumulating over time, however. Maybe there could be an open issue in the tracker that documents this state of affairs.

**Pull request closed without merging**
