### PR TITLE
Update for Xcode 8 / Swift 3

### PR DESCRIPTION
**Pull request by IngmarStein**
This commit renames `ErrorProtocol` to `Error` and splits a complex expression into smaller ones (to help the compiler with type checking).

### CODE REVIEW

**Comment by IngmarStein** [comment]
This has turned out to be more extensive than expected. I renamed the `CommandLine` module to `CommandLineKit` in order not to clash with the new `Swift.CommandLine` class (see #77). Before this PR, it was hard to use `CommandLine.ParseError` (now it can be accessed as `CommandLineKit.CommandLine.ParseError`).

While testing locally with a locale that uses ',' as the decimal separator (German), I found that the tests expect a locale that uses '.'. So I fixed this along the way. Also, I removed `CommandLine.swift`, `Option.swift` and `StringExtensions.swift` from the test target (unnecessary, because they're imported as a module).

**Comment by tflo** [comment]
Thanks for sharing this really great CL framework!

I checked it out with the #78 pull request and it works fine so far with my Swift 3 project, with Xcode 8b6. (Source files added to target.)

**Comment by jatoben** [comment]
Thanks for doing the heavy lifting here @IngmarStein! ⚡ 

I'm fine with renaming the module to CommandLineKit (cc #77), but do you think we should also rename the CommandLine class? `CommandLineKit.CommandLine.ParseError.InvalidValueForOption` seems a bit clunky to me. It could also be hoisted out of the CommandLine class, I suppose.

**Comment by IngmarStein** [comment]
I thought about renaming the `CommandLine` class as well, but I didn't want to call it the same as the framework, because that name is not a good description of its functionality and there's no precedence from Apple (e.g. there are no `UIKit` or `Foundation` classes).
I briefly wanted to rename it to `CommandLineParser` but decided against it for backwards compatibility reasons. Your call… I'll happily update this PR or you can do it after merging.

**Comment by IngmarStein** [comment]
This PR removes compatibility with Xcode 7 / Swift 2.x, now that Xcode 8 has been out for a while.

**Comment by IngmarStein** [comment]
Pinging @jatoben

**Comment by klaas** [comment]
I would really like to see this PR integrated.

**Comment by jatoben** [comment]
Thanks for all the heavy lifting here @IngmarStein and sorry for the delay on my part!

**Pull request merged**
